#' Repositorio Teórico de Estadística No Paramétrica (EP4146)
#'
#' @description
#' These functions are used to subset a data frame, applying the expressions in ... to determine which rows should be kept (for filter()) or dropped ( for filter_out()). Multiple conditions can be supplied separated by a comma. These will be combined with the & operator. To combine comma separated conditions using | instead, wrap them in when_any(). Both filter() and filter_out() treat NA like FALSE. This subtle behavior can impact how you write your conditions when missing values are involved. See the section on ⁠Missing values⁠ for important details and examples.
#' solo dame la clave
#'
#'
#' 01 — Anderson-Darling k muestras (Independientes · Forma)
#' La prueba de Anderson-Darling para k muestras es la única del capítulo 5 cuyo objetivo es evaluar si k muestras independientes provienen de poblaciones con la misma distribución (forma), sin necesidad de especificar cuál distribución teórica. No es una prueba de posición ni de escala — compara la función de distribución empírica de cada grupo contra la función de distribución empírica combinada de todos los datos. A diferencia de Kolmogorov-Smirnov (que solo mira la diferencia máxima), Anderson-Darling da mayor peso a las colas por ser una prueba cuadrática. Sus únicos supuestos son que la variable sea cuantitativa y que las k muestras sean aleatorias e independientes — no exige normalidad, no exige igual forma previa. El estadístico crudo ADK no se usa directamente: se estandariza como T.AD = (ADK − media) / sigma, donde la media y sigma los reporta R automáticamente, y el p-valor se obtiene como pnorm(T.AD, lower.tail=FALSE) porque es prueba de cola derecha. Si T.AD es negativo el p-valor será cercano a 1 (los grupos son muy similares). Trampa crítica: si los grupos tienen medianas distintas, AD rechazará H₀ aunque la forma sea idéntica — detecta la diferencia de locación. Para evitarlo se corrige restando la mediana de cada grupo (distribución asimétrica) o la media (simétrica) antes de aplicar la prueba. No realiza comparaciones múltiples. Su rol en el análisis es siempre ser la primera prueba — verifica el supuesto de igualdad de forma que exigen Kruskal-Wallis y Van der Waerden. Si se rechaza H₀ → no se pueden aplicar KW ni VdW, solo la Prueba de la Mediana.
#' Palabras clave: distribución igual, forma, misma distribución, antes de proceder, verifique.
#'
#' 02 — Prueba de la Mediana (Independientes · Posición)
#' La Prueba de la Mediana evalúa si k muestras independientes tienen la misma mediana poblacional, clasificando cada observación simplemente como mayor o menor a la mediana global combinada de todos los grupos. Con esas clasificaciones arma una tabla de contingencia k×2 y aplica Chi cuadrado sobre ella. Sus supuestos son solo dos: variable cuantitativa y muestras aleatorias e independientes — no exige igualdad de forma, lo que la convierte en la única prueba de posición aplicable cuando Anderson-Darling rechaza H₀. Esta ventaja tiene un costo: al dicotomizar la información pierde potencia frente a Kruskal-Wallis o Van der Waerden. El estadístico sigue una distribución Chi cuadrado con k-1 grados de libertad y el p-valor se calcula como pchisq(chi2, df=k-1, lower.tail=FALSE). Cuando hay frecuencias esperadas pequeñas se aplica la corrección de Yates (correct=TRUE) que sustrae 0.5 del valor absoluto de cada diferencia para evitar sobreestimar la significancia. Sí realiza comparaciones múltiples por pares con Median.test(..., group=FALSE). No genera IC directamente — para IC de la mediana de cada grupo se usa SIGN.test() del paquete BSDA individualmente por grupo.
#' Palabras clave: clasificación respecto a la mediana, mediana global, mayor o menor, basada en la mediana.
#'
#' 03 — Kruskal-Wallis (Independientes · Posición)
#' Kruskal-Wallis es la alternativa no paramétrica del ANOVA de un factor (DCA) y evalúa si k muestras independientes tienen la misma mediana poblacional, basándose en el rankeo conjunto de todas las observaciones. Rankea todas las observaciones de los k grupos juntas de menor a mayor, suma los rangos de cada grupo y evalúa si esas sumas son demasiado distintas para ser atribuibles al azar. Sus supuestos son: muestras aleatorias mutuamente excluyentes, variable de escala al menos intervalo, y las poblaciones tienen la misma distribución (igual forma) difiriendo solo en su localización — este tercer supuesto es explícito en el PDF del profe y por eso Anderson-Darling va antes. El estadístico H sigue una distribución Chi cuadrado con k-1 grados de libertad; cuando hay empates R corrige automáticamente. El p-valor se calcula como pchisq(H, df=k-1, lower.tail=FALSE). Para comparaciones múltiples usa kruskal() de agricolae que reporta LCL y UCL para la diferencia de rangos promedio entre pares — si el IC no contiene el 0, los grupos difieren. Trampa crítica del output: la columna "means" de kruskal() reporta rangos promedio de cada grupo, no las medias originales. kruskal.test() de base R solo da el estadístico global sin comparaciones — siempre usar kruskal() de agricolae en el examen. Si AD rechaza H₀ → no aplica KW.
#' Palabras clave: rankeo de las observaciones, basada en rangos, sin especificar mecanismo.
#'
#' 04 — Van der Waerden (Independientes · Posición)
#' Van der Waerden evalúa si k muestras independientes tienen la misma mediana poblacional, convirtiendo los rankeos en cuantiles de la distribución normal estándar — de ahí el nombre "puntuaciones normales". El proceso: rankear todas las observaciones conjuntamente, calcular Aᵢⱼ = Φ⁻¹(R(Xᵢⱼ)/(n+1)) para cada observación, y comparar los promedios de esas puntuaciones normales (Āᵢ) entre grupos. Sus supuestos son idénticos a Kruskal-Wallis: variable de escala al menos intervalo e igualdad de forma entre poblaciones — también requiere Anderson-Darling previo. La ventaja exclusiva de VdW sobre KW: cuando los datos provienen de una distribución normal su eficiencia asintótica respecto al ANOVA paramétrico es igual a 1 — es tan potente como el ANOVA. El estadístico T₁ sigue una distribución Chi cuadrado con k-1 grados de libertad y el p-valor se calcula como pchisq(T1, df=k-1, lower.tail=FALSE). Sí realiza comparaciones múltiples con waerden.test(..., group=FALSE). Trampa crítica del output: la columna "means" de waerden.test() reporta los promedios de puntuaciones normales (Āᵢ), no las medias originales — el grupo con mayor Āᵢ tiene la mediana más alta, pero el valor numérico es el cuantil normal, no la media real. Si AD rechaza H₀ → no aplica VdW.
#' Palabras clave: puntuaciones normales, valores normales, cuantiles normales, normal scores.
#'
#' 05 — Jonckheere-Terpstra (Independientes · Tendencia)
#' Jonckheere-Terpstra detecta tendencia ordenada en k muestras independientes — no simplemente "hay diferencias en alguno", sino que las medianas siguen un orden creciente o decreciente según el orden natural de los grupos. Su lógica cuenta cuántas observaciones de un grupo de mayor orden superan a las de un grupo de menor orden, acumulando esa información en el estadístico JT. No exige igualdad de forma como supuesto explícito — no requiere Anderson-Darling previo. Sus supuestos son: variable de escala al menos intervalo y que exista un orden natural entre los k grupos. Las hipótesis siempre son: H₀ igualdad de medianas; H₁ tendencia (creciente o decreciente) con al menos una desigualdad estricta — H₀ nunca es la tendencia, siempre es la igualdad. El estadístico JT se estandariza antes del p-valor: Z = (JT − μJT) / σJT, donde μJT = (n² − Σnᵢ²)/4, y el p-valor se obtiene como pnorm(Z, lower.tail=FALSE) para tendencia creciente. En R se especifica alternative="increasing" o alternative="decreasing". No realiza comparaciones múltiples. Trampa del enunciado: si menciona el orden de los grupos pero NO dice "aumenta/disminuye a medida que", la prueba es KW (diferencias generales), no JT. La confusión más frecuente es con Page: JT es para k independientes, Page es para k relacionadas.
#' Palabras clave: aumenta a medida que, disminuye a medida que, tendencia creciente, tendencia decreciente, grupos con orden natural.
#'
#' 06 — Levene (Independientes · Escala)
#' La prueba de Levene evalúa si k muestras independientes tienen el mismo parámetro de dispersión (varianza) y es la alternativa no paramétrica a la prueba de Bartlett. Su mecanismo: calcula una medida de posición de cada grupo (media, mediana o media podada al 10%) y a cada observación le resta esa medida, obteniendo las desviaciones absolutas Zᵢⱼ = |Yᵢⱼ − Ȳᵢ|. Luego aplica un estadístico tipo F sobre esas desviaciones, comparando si los grupos de Zᵢⱼ son similares entre sí. La versión que usa la mediana (Brown-Forsythe) es más robusta cuando hay no-normalidad. El estadístico W sigue una distribución F con df1=k-1 y df2=n-k — el p-valor se calcula como pf(W, df1=k-1, df2=n-k, lower.tail=FALSE). Sus supuestos son: muestras independientes, muestras aleatorias y variable cuantitativa continua. No realiza comparaciones múltiples directamente — si se rechaza H₀ se complementa con Conover para identificar qué grupos difieren. La diferencia con Fligner-Killeen: Levene va directamente de las desviaciones absolutas al estadístico F, mientras que Fligner-Killeen convierte esas desviaciones a puntuaciones normales antes del estadístico Chi cuadrado.
#' Palabras clave: desviaciones absolutas respecto a la mediana, desviaciones absolutas respecto a la media, variabilidad, dispersión.
#'
#' 07 — Fligner-Killeen (Independientes · Escala)
#' Fligner-Killeen evalúa si k muestras independientes tienen el mismo parámetro de escala usando una función de puntuación basada en la distribución normal estándar. Su mecanismo: resta la mediana de cada grupo a cada observación (Zᵢⱼ = |Xᵢⱼ − medianaᵢ|), rankea esas desviaciones absolutas sin importar el grupo de origen, y convierte esos rangos a puntuaciones normales Φ⁻¹. El estadístico sigue una distribución Chi cuadrado con k-1 grados de libertad. Sus supuestos son: muestras aleatorias y variable cuantitativa continua — no exige igualdad de medianas entre grupos, lo que la diferencia de Klotz. Por eso es más adecuada para distribuciones asimétricas o con colas pesadas, donde las medianas de los grupos pueden ser distintas. Es función base de R: fligner.test(y, g) sin necesidad de paquetes. No realiza comparaciones múltiples — si se rechaza H₀ se complementa con Conover. El p-valor se calcula como pchisq(FK, df=k-1, lower.tail=FALSE). La confusión más frecuente es con Klotz: ambas usan "función de puntuación", pero Fligner-Killeen no exige igual mediana y Klotz sí.
#' Palabras clave: función de puntuación, medianas distintas entre grupos, distribución asimétrica, colas pesadas.
#'
#' 08 — Klotz (Independientes · Escala)
#' La prueba de Klotz evalúa si k muestras independientes tienen el mismo parámetro de escala usando también una función de puntuación, pero con una diferencia clave respecto a Fligner-Killeen: rankea directamente las observaciones (sin restar la mediana) y convierte esos rangos al cuadrado del cuantil normal [Φ⁻¹]². La lógica parte de que si las muestras tienen la misma dispersión, sus rangos deberían distribuirse uniformemente al combinarlas. A diferencia de Fligner-Killeen, Klotz sí exige igualdad de medianas entre grupos como supuesto — si las medianas difieren, las diferencias de dispersión se confundirán con diferencias de locación. Por eso es más adecuada para distribuciones simétricas donde las medianas son similares entre grupos. El estadístico sigue una distribución Chi cuadrado con k-1 grados de libertad. A diferencia de Fligner-Killeen, Klotz sí realiza comparaciones múltiples por pares. Se implementa con klotz_test(y~g) del paquete coin.
#' Palabras clave: función de puntuación, medianas iguales, distribución simétrica, Klotz.
#'
#' 09 — Conover (Independientes · Escala)
#' La prueba de Conover evalúa si k muestras independientes tienen el mismo parámetro de escala usando rangos al cuadrado centrados respecto a la media de cada grupo. Su mecanismo: calcula las desviaciones de cada observación respecto a la media de su grupo, las eleva al cuadrado, las rankea todas juntas y compara esas sumas de rangos cuadrados entre grupos. El estadístico sigue una distribución Chi cuadrado con k-1 grados de libertad. Sus supuestos son: variable cuantitativa y muestras independientes — no exige igualdad de medianas. A diferencia de Levene y Fligner-Killeen, Conover sí realiza comparaciones múltiples por pares directamente usando un estadístico t — por eso es la prueba de escala que el profe usa para identificar qué grupos difieren cuando se rechaza H₀. Se implementa con conover_test(y~g) del paquete coin. El p-valor de la prueba global se calcula como pchisq(T, df=k-1, lower.tail=FALSE).
#' Palabras clave: según Conover, rangos al cuadrado, comparaciones de dispersión por pares.
#'
#' 10 — Q de Cochran (Relacionadas · Dicotómica)
#' La prueba Q de Cochran evalúa si k tratamientos o condiciones aplicados a los mismos n sujetos producen proporciones de éxito iguales, cuando la variable respuesta es dicotómica (0/1). Es la extensión de McNemar para más de 2 grupos relacionados — diseño idéntico al DBCA pero con variable de respuesta binaria. Los supuestos son: muestra aleatoria de tamaño n y la variable respuesta es dicotómica o puede ser dicotomizada. El estadístico Q sigue una distribución Chi cuadrado con k-1 grados de libertad y se calcula como pchisq(Q, df=k-1, lower.tail=FALSE). Las hipótesis son sobre proporciones (p₁ = p₂ = ... = pₖ), no sobre medianas. No requiere Anderson-Darling previo. Se implementa con cochran.qtest(res~tra|blo) del paquete RVAideMemoire — la barra | separa el tratamiento del bloque. Trampa del enunciado: si dice "proporción de pacientes que logró X con cada tratamiento" y los mismos pacientes reciben todos los tratamientos → Q de Cochran. Si fueran grupos independientes → prueba Chi cuadrado de capítulos anteriores.
#' Palabras clave: proporción, variable dicotómica, sí/no, éxito/fracaso, 0/1, mismos sujetos.
#'
#' 11 — Friedman (Relacionadas · Posición)
#' La prueba de Friedman es la alternativa no paramétrica del ANOVA de bloques (DBCA) y evalúa si k tratamientos aplicados a los mismos b bloques producen la misma mediana de respuesta. Su mecanismo rankea las observaciones dentro de cada bloque (de 1 a k) y compara si las sumas de rangos de cada tratamiento son significativamente distintas — el rankeo intra-bloque es lo que diferencia a Friedman de Kruskal-Wallis. Sus supuestos son: bloques mutuamente independientes y variable de escala al menos ordinal — no exige normalidad, no exige igualdad de varianzas, no requiere Anderson-Darling previo. Exige bloques completos: todos los bloques deben tener medición en todos los tratamientos. El estadístico Fr sigue una distribución Chi cuadrado con k-1 grados de libertad y el p-valor se calcula como pchisq(Fr, df=k-1, lower.tail=FALSE). Sí realiza comparaciones múltiples con friedman(..., group=FALSE) de agricolae. Se usa cuando los bloques son homogéneos entre sí — si hay mucha variabilidad entre bloques, Quade es más potente.
#' Palabras clave: mismos sujetos, k tratamientos, bloques completos, bloques homogéneos, DBCA no paramétrico.
#'
#' 12 — Quade (Relacionadas · Posición)
#' La prueba de Quade es una alternativa a Friedman que evalúa si k tratamientos aplicados a los mismos b bloques producen la misma mediana, pero ponderando los bloques según su variabilidad. El mecanismo rankea dentro de cada bloque (igual que Friedman) pero además calcula el rango del rango de cada bloque — los bloques con mayor dispersión interna reciben más peso en el estadístico. Esto la hace más potente que Friedman cuando los bloques son heterogéneos entre sí. Sus supuestos son: bloques independientes, variable de escala al menos de intervalo (más exigente que Friedman que solo pide ordinal) y bloques completos. El estadístico de Quade sigue una distribución F con df1=k-1 y df2=(b-1)(k-1) — a diferencia de Friedman que usa Chi cuadrado. El p-valor se calcula como pf(F, df1=k-1, df2=(b-1)(k-1), lower.tail=FALSE). Sí realiza comparaciones múltiples con quadeAllPairsTest() de PMCMRplus. No requiere Anderson-Darling previo.
#' Palabras clave: mucha variabilidad entre bloques, bloques heterogéneos, perfiles muy distintos, prueba más potente.
#'
#' 13 — Page (Relacionadas · Tendencia)
#' La prueba de Page es la extensión de Friedman para detectar tendencia ordenada en k muestras relacionadas — es la contraparte de Jonckheere-Terpstra pero para la estructura de bloques. Mientras Friedman prueba "¿hay diferencias en algún tratamiento?", Page prueba "¿los tratamientos siguen un orden creciente o decreciente en sus medianas?". El mecanismo rankea dentro de cada bloque (igual que Friedman) y calcula el estadístico L = Σᵢ i·Rᵢ que pondera más a los tratamientos de mayor orden. Sus supuestos son: bloques mutuamente independientes y variable de escala al menos ordinal — no requiere Anderson-Darling previo. Exige bloques completos. El estadístico L se aproxima a una distribución normal para muestras grandes. En R se usa PageTest() de DescTools — no tiene argumento alternative: para tendencia decreciente hay que invertir el orden de las columnas de la matriz. Las hipótesis: H₀ igualdad de medianas; H₁ tendencia con al menos una desigualdad estricta. El orden debe especificarse a priori. Confusión frecuente: Page es para k relacionadas; JT es para k independientes.
#' Palabras clave: aumenta a medida que, tendencia creciente, mismos sujetos, dosis escalonada, orden a priori.
#'
#' 14 — Durbin (Relacionadas · Posición)
#' La prueba de Durbin es una alternativa a Friedman para diseños en bloques incompletos balanceados y planificados — cuando desde el inicio del estudio se diseñó que cada bloque evaluaría solo t de los k tratamientos, de forma sistemática y equilibrada. La incompletitud en Durbin no es accidental sino intencional y balanceada: cada tratamiento aparece el mismo número de veces en los bloques, y cada par de tratamientos aparece juntos en el mismo número de bloques. Sus supuestos son: variable de escala al menos ordinal, bloques independientes y diseño incompleto balanceado. El estadístico sigue una distribución Chi cuadrado con k-1 grados de libertad. Sí realiza comparaciones múltiples con durbin.test(..., group=FALSE) de agricolae. No requiere Anderson-Darling previo. La distinción crítica con Skillings-Mack: Durbin es para incompletitud planificada y balanceada; Skillings-Mack es para datos faltantes accidentales.
#' Palabras clave: diseño incompleto balanceado, cada bloque evalúa t de k tratamientos, diseñado así desde el inicio, incompleto planificado.
#'
#' 15 — Skillings-Mack (Relacionadas · Posición)
#' La prueba de Skillings-Mack es una generalización de Friedman para diseños en bloques con datos faltantes arbitrarios y accidentales — cuando algunos bloques no pudieron ser evaluados en ciertos tratamientos por razones no planificadas (problemas operativos, datos mal digitados, abandono). A diferencia de Friedman (que exige bloques completos) y Durbin (que exige incompletitud planificada y balanceada), Skillings-Mack maneja cualquier patrón de datos faltantes. Sus supuestos son: variable de escala al menos ordinal y bloques mutuamente independientes. El p-valor se basa en la distribución Chi cuadrado aproximada por Monte Carlo. En R se implementa con Ski.Mack(matriz) del paquete Skillings.Mack — recibe una matriz con NA donde faltan datos, con filas=bloques y columnas=tratamientos. No requiere Anderson-Darling previo. La confusión más frecuente en el C2 es invertir Durbin y Skillings-Mack.
#' Palabras clave: datos faltantes accidentales, problemas operativos, no pudo ser evaluado, datos mal digitados, incompletitud no planificada.
#'
#' 16 — Scheirer-Ray-Hare (Independientes · Posición · Dos factores)
#' La prueba de Scheirer-Ray-Hare es el equivalente no paramétrico del ANOVA bifactorial — evalúa el efecto de dos factores independientes (A y B) y su interacción (A×B) sobre una variable respuesta cuando no se cumple la normalidad. El mecanismo rankea todas las observaciones conjuntamente y aplica la lógica del ANOVA sobre esos rangos. Sus supuestos include: variable de escala al menos intervalo, observaciones independientes, misma forma de distribución en todos los grupos (exige igualdad de forma → requiere Anderson-Darling previo) y al menos 5 repeticiones por celda. El estadístico de cada efecto sigue una distribución Chi cuadrado con los grados de libertad del efecto respectivo. Procedimiento crítico: siempre verificar la interacción primero — si la interacción A×B es significativa, no se interpretan los efectos principales A y B por separado. Se implementa con scheirerRayHare(y~A+B, data=datos) del paquete rcompanion.
#' Palabras clave: dos factores, diseño factorial, efecto de interacción, experimento factorial, A×B.
#'
#' 17-18 — Prueba de Permutación (Independientes y Relacionadas · Posición)
#' Las pruebas de permutación son alternativas al ANOVA cuando ninguno de sus supuestos se cumple — no requieren normalidad, no requieren igualdad de varianzas, no requieren Anderson-Darling previo y no dependen de ninguna distribución teórica. Generan su propia distribución empírica por simulación: permutan las observaciones entre grupos (k independientes) o dentro de cada bloque (k relacionadas) miles de veces y calculan qué proporción de esas permutaciones produce un estadístico igual o más extremo que el observado — esa proporción es el p-valor. Para k independientes permuta las n observaciones entre los k grupos; para k relacionadas permuta dentro de cada bloque respetando su estructura. Sus supuestos son mínimos: muestras aleatorias y para la versión relacionada, bloques independientes entre sí. En R se implementa con aovp(y~g) o aovp(y~g+blo) del paquete lmPerm. La diferencia entre la versión independiente y relacionada es conceptualmente igual a la diferencia entre ANOVA DCA y ANOVA DBCA.
#' Palabras clave: prueba de permutación, sin supuestos distribucionales, distribución empírica, simulación.
#'
#' @param .data Un data frame o tibble.
#' @param ... Expresiones lógicas para filtrar.
#' @param .by Parámetro opcional para agrupamiento rápido.
#' @param .preserve Preservar la estructura de los factores.
#'
#' @export
filter <- function(.data, ..., .by = NULL, .preserve = FALSE) {
  # Contenedor de la documentación teórica.
  # Esta función simula la estructura de filtrado estructural en el paquete.
}

#' @rdname filter
#' @export
filter_out <- function(.data, ..., .by = NULL, .preserve = FALSE) {
  # Contraparte complementaria de la función filter
}
